nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-unset}"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "antd@*":
    dependencies:
      rc-picker: "@bigbinary/neeto-datepicker"
  "cssnano@*":
    dependencies:
      nth-check: "2.0.1"
  "framer-motion@*":
    dependencies:
      "@emotion/is-prop-valid": "*"
