version: v1.0

plan: standard-2

paths:
  - src/**
  - tests/**
  - stories/**
  - jest-config/**
  - jest-setup.js
  - .scripts/*
  - .neetoci/default.yml
  - package.json
  - yarn.lock
  - .yarnrc.yml
  - .node-version
  - .nvmrc
  - .browserslistrc
  - .prettierrc.js
  - .eslintignore
  - .eslintrc.js
  - "*.config.*"

global_job_config:
  setup:
    - checkout
    - neetoci-version node 22.13
    - cache restore
    - corepack enable
    - yarn set version 4.9.2
    - yarn install
    - cache store
  jobs:
    - name: CiChecks
      commands:
        - .scripts/run_eslint_on_modified_files.sh
        - yarn test --detectOpenHandles

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
